const properties = [
  {
    id: 1,
    title: "Nyarutarama Luxury Residence",
    location: "Nyarutarama",
    type: "Apartment",
    status: "For Rent",
    bedrooms: 3,
    bathrooms: 2,
    size: 180,
    price: 1500000,
    priceLabel: "RWF 1,500,000 /month",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
    description: "Experience luxury living in the heart of Nyarutarama. This apartment offers panoramic views, modern amenities, and 24/7 security.",
    coordinates: { lat: -1.936, lng: 30.098 },
    dateAdded: "2024-03-15",
    views: 1245,
    isFeatured: true
  },
  {
    id: 2,
    title: "Kiyovu Modern Home",
    location: "Kiyovu",
    type: "House",
    status: "For Sale",
    bedrooms: 4,
    bathrooms: 3,
    size: 280,
    price: 380000000,
    priceLabel: "RWF 380,000,000",
    image: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2080&q=80",
    description: "A stunning modern home located in the prestigious Kiyovu neighborhood. Features a beautifully landscaped garden and spacious interiors.",
    coordinates: { lat: -1.947, lng: 30.063 },
    dateAdded: "2024-04-20",
    views: 870,
    isFeatured: false
  },
  {
    id: 3,
    title: "Kimihurura Short Stay Apartment",
    location: "Kimihurura",
    type: "Apartment",
    status: "Short Stay",
    bedrooms: 2,
    bathrooms: 2,
    size: 120,
    price: 80000,
    priceLabel: "RWF 80,000 /night",
    image: "https://images.unsplash.com/photo-1600566752355-35792bedcfea?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
    description: "Perfect for business travelers or tourists. This fully furnished apartment in Kimihurura offers easy access to the city center and local restaurants.",
    coordinates: { lat: -1.954, lng: 30.091 },
    dateAdded: "2024-05-10",
    views: 2150,
    isFeatured: true
  },
  {
    id: 4,
    title: "Gisozi Modern Studio",
    location: "Gisozi",
    type: "Studio",
    status: "For Rent",
    bedrooms: 1,
    bathrooms: 1,
    size: 70,
    price: 650000,
    priceLabel: "RWF 650,000 /month",
    image: "apartment8.png",
    description: "A cozy and modern studio apartment in Gisozi, perfect for a young professional. Features open plan living and high-speed internet.",
    coordinates: { lat: -1.930, lng: 30.070 },
    dateAdded: "2024-05-25",
    views: 530,
    isFeatured: false
  },
  {
    id: 5,
    title: "Remera Family Apartment",
    location: "Remera",
    type: "Apartment",
    status: "For Rent",
    bedrooms: 4,
    bathrooms: 3,
    size: 220,
    price: 1800000,
    priceLabel: "RWF 1,800,000 /month",
    image: "serrr2.png",
    description: "Spacious family apartment located in Remera. Close to international schools, shopping malls, and the Amahoro Stadium.",
    coordinates: { lat: -1.957, lng: 30.117 },
    dateAdded: "2024-06-01",
    views: 1100,
    isFeatured: true
  },
  {
    id: 6,
    title: "Kicukiro Sky Penthouse",
    location: "Kicukiro",
    type: "Penthouse",
    status: "For Rent",
    bedrooms: 2,
    bathrooms: 2,
    size: 150,
    price: 1300000,
    priceLabel: "RWF 1,300,000 /month",
    image: "https://images.unsplash.com/photo-1560448205-4d9b3e6bb6db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
    description: "Luxurious penthouse in Kicukiro with breathtaking views of the city. Features a private terrace and premium finishings.",
    coordinates: { lat: -1.975, lng: 30.100 },
    dateAdded: "2024-06-15",
    views: 3200,
    isFeatured: true
  },
  {
    id: 7,
    title: "Kimihurura Garden View",
    location: "Kimihurura",
    type: "Apartment",
    status: "For Rent",
    bedrooms: 3,
    bathrooms: 2,
    size: 200,
    price: 1600000,
    priceLabel: "RWF 1,600,000 /month",
    image: "https://images.unsplash.com/photo-1554469384-e58fac16e23a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80",
    description: "Enjoy peaceful living with a beautiful garden view in Kimihurura. This apartment is spacious and filled with natural light.",
    coordinates: { lat: -1.955, lng: 30.092 },
    dateAdded: "2024-06-20",
    views: 950,
    isFeatured: false
  },
  {
    id: 8,
    title: "Gikondo Cozy Studio",
    location: "Gikondo",
    type: "Studio",
    status: "For Rent",
    bedrooms: 1,
    bathrooms: 1,
    size: 60,
    price: 600000,
    priceLabel: "RWF 600,000 /month",
    image: "https://images.unsplash.com/photo-1560448205-97abe7378152?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80",
    description: "Compact, well-designed studio in Gikondo. Ideal for singles looking for an affordable yet stylish living space.",
    coordinates: { lat: -1.970, lng: 30.080 },
    dateAdded: "2024-07-02",
    views: 740,
    isFeatured: false
  },
  {
    id: 9,
    title: "Kacyiru Executive Suite",
    location: "Kacyiru",
    type: "Apartment",
    status: "For Rent",
    bedrooms: 4,
    bathrooms: 3,
    size: 250,
    price: 2100000,
    priceLabel: "RWF 2,100,000 /month",
    image: "ser111.png",
    description: "Executive suite in Kacyiru, offering premium amenities, a swimming pool, and proximity to embassies and ministries.",
    coordinates: { lat: -1.940, lng: 30.085 },
    dateAdded: "2024-07-10",
    views: 1800,
    isFeatured: true
  },
  {
    id: 10,
    title: "Rebero Hilltop Villa",
    location: "Rebero",
    type: "Villa",
    status: "For Sale",
    bedrooms: 5,
    bathrooms: 4,
    size: 450,
    price: 650000000,
    priceLabel: "RWF 650,000,000",
    image: "house 1.JPG",
    description: "Magnificent hilltop villa in Rebero with stunning 360-degree views. Features a private pool, large garden, and multiple entertainment areas.",
    coordinates: { lat: -1.995, lng: 30.088 },
    dateAdded: "2024-07-25",
    views: 4500,
    isFeatured: true
  },
  {
    id: 11,
    title: "Kibagabaga Family House",
    location: "Kibagabaga",
    type: "House",
    status: "For Rent",
    bedrooms: 4,
    bathrooms: 3,
    size: 300,
    price: 2000000,
    priceLabel: "RWF 2,000,000 /month",
    image: "house for rent.png",
    description: "Beautiful family house in a serene neighborhood of Kibagabaga. Excellent security and close to international amenities.",
    coordinates: { lat: -1.930, lng: 30.120 },
    dateAdded: "2024-08-05",
    views: 1320,
    isFeatured: false
  }
];

// Global locations for the autocomplete and dropdowns
const rwandaLocations = [
  "Nyarutarama", "Kiyovu", "Kacyiru", "Kimihurura", "Gikondo", 
  "Kicukiro", "Remera", "Gisozi", "Kagarama", "Niboye", 
  "Kanombe", "Rebero", "Kibagabaga", "Ndera"
];
